### ISSUE TITLE
Test Auton to see if works

### ISSUE THREAD

**Issue by kgminer** [Mercury1089/2016-robot-code#17]

**Comment by gartaud** [comment]
Now that auton is working from the first starting position, expand the approach to support other starting positions. One approach could be to print the field map. Then trace lines straight out of the center of each starting position and of each tower opening. Where (if) the lines intersect is where the robot should turn. Measure the distance from the exit of the defense to that point so that you know by how much the robot should move after breaching the defense. Then measure the angle so that you know by how much the robot should turn to be facing an opening. Finally check if the robot should move forward after turning to be at the optimal shooting distance. If the lines do not intersect assess if the robot is facing an opening "enough" so that a shot can be made without turning.
Then  consider increasing the speed of the moves after breaching the defenses. 6V might be a good compromise between speed and stability.
Also because the turns described above do not have to be super precise we may want to implement a fast turn method (virtually same as the current turning method, but with a lower dmax (maybe 45 degrees?) and larger exit condition (maybe 5 degrees?)

**Comment by gartaud** [comment]
Suggesting adding a MOVE1 state after CENTER and before ROTATE1.
BREACH would remain at low speed (4.5V), and just go slightly past defense, then CENTER to make sure we are straight, then MOVE1 at high speed up (6V) to the position ROTATE1
(and MOVE would become MOVE2)

**Comment by gartaud** [comment]
See also #19

**Comment by DrewTheRat** [comment]
I believe we can close this issue. We did auton testing (albeit limited) pre-Seneca. We did more extensive auton testing leading up to Monty. We have also significantly revised autons.
